import type { Product } from "./types";

const additionalProducts: Product[] = [
  {
    id: "ng-blouse-07",
    name: "Saffron Mirror",
    nameIsPlaceholder: false,
    slug: "saffron-mirror",
    category: "blouse",
    categoryLabel: "Embroidered blouse",
    price: 1650,
    priceIsEstimate: true,
    images: ["/products/blouse-04.png"],
    study: "saffron",
    silhouette: "blouse",
    description: "A warm orange-red sleeveless blouse with colourful floral motifs, mirror accents and scalloped edging.",
    catalogNotes: ["Sleeveless cut", "Mirror accents", "Estimated price"],
    sizes: ["Catalog size unspecified"],
    colorName: "Orange-red",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["blouse", "orange", "red", "mirror", "floral", "embroidered"],
    collection: "Blouse Stories",
    moods: ["festive", "rang", "statement"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-blouse-08",
    name: "Laal Sheesha",
    nameIsPlaceholder: false,
    slug: "laal-sheesha",
    category: "padded-blouse",
    categoryLabel: "Mirror-work blouse",
    price: 1750,
    priceIsEstimate: true,
    images: ["/products/blouse-05.png"],
    study: "maroon",
    silhouette: "blouse",
    description: "A red-orange sleeveless blouse with dense multicolour mirror-style detailing across the front.",
    catalogNotes: ["Sleeveless cut", "Mirror-style detailing", "Estimated price"],
    sizes: ["Catalog size unspecified"],
    colorName: "Red-orange",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["blouse", "red", "orange", "mirror", "embroidered", "choli"],
    collection: "Blouse Stories",
    moods: ["festive", "party", "statement"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-jacket-02",
    name: "Hari Chakra Layer",
    nameIsPlaceholder: false,
    slug: "hari-chakra-layer",
    category: "jacket",
    categoryLabel: "Sleeveless cropped layer",
    price: 2850,
    priceIsEstimate: true,
    images: ["/products/jacket-02.png"],
    study: "emerald",
    silhouette: "jacket",
    description: "A deep-green sleeveless cropped layer with bright circular trim along the neckline, arm openings and hem.",
    catalogNotes: ["Sleeveless cropped layer", "Multicolour circular trim", "Estimated price"],
    sizes: ["Catalog size unspecified"],
    colorName: "Forest green",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["jacket", "layer", "green", "mirror", "circular trim", "sleeveless"],
    collection: "The Jacket Edit",
    moods: ["festive", "statement", "rang"],
    featured: true,
    pieces: ["jacket"],
  },
  {
    id: "ng-jacket-03",
    name: "Jamuni Paisley Layer",
    nameIsPlaceholder: false,
    slug: "jamuni-paisley-layer",
    category: "jacket",
    categoryLabel: "Sleeveless cropped layer",
    price: 2950,
    priceIsEstimate: true,
    images: ["/products/jacket-03.png"],
    study: "magenta",
    silhouette: "jacket",
    description: "A purple sleeveless cropped layer with an all-over orange, pink and gold paisley pattern.",
    catalogNotes: ["Sleeveless cropped layer", "Paisley print", "Estimated price"],
    sizes: ["Catalog size unspecified"],
    colorName: "Purple",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["jacket", "layer", "purple", "paisley", "printed", "sleeveless"],
    collection: "The Jacket Edit",
    moods: ["festive", "mehfil", "statement"],
    featured: true,
    pieces: ["jacket"],
  },
];

export { additionalProducts };
