export const journal = [
  {
    slug: "craft",
    kicker: "Craft",
    title: "The cut is the craft",
    excerpt: "A blouse that can leave the set. A jacket that changes the hour. A skirt that holds the volume.",
    href: "/story#form",
  },
  {
    slug: "styling",
    kicker: "Styling",
    title: "How to style a 3-piece set",
    excerpt: "Wear it complete. Or keep the skirt, change the blouse, add the jacket when the day turns.",
    href: "/story#movement",
  },
  {
    slug: "story",
    kicker: "The story behind the look",
    title: "An old language. A new silhouette.",
    excerpt: "Indian form, styled for a wardrobe that also owns denim, a blazer, a night out.",
    href: "/story#heritage",
  },
  {
    slug: "tradition-now",
    kicker: "Tradition / now",
    title: "Not costume. Clothes.",
    excerpt: "The point is not to look traditional. The point is to look like yourself, with heritage still in the cloth.",
    href: "/story#self",
  },
] as const;

export const lookbookChapters = [
  {
    id: "edit",
    index: "01",
    title: "The Nav Edit",
    copy: "Three pieces, one attitude. Start here if you want the wardrobe in a single glance.",
    study: "gulnaar" as const,
    silhouette: "set" as const,
    image: "/products/lehenga-18.png",
    href: "/collections/the-nav-edit",
    cta: "Shop the edit",
  },
  {
    id: "blouse",
    index: "02",
    title: "The blouse, alone",
    copy: "Free-size, including padded styles. The piece that lets a set become a sentence you can rewrite.",
    study: "ivory" as const,
    silhouette: "blouse" as const,
    image: "/products/blouse-06.png",
    href: "/shop/blouses",
    cta: "Shop blouses",
  },
  {
    id: "jacket",
    index: "03",
    title: "The modern layer",
    copy: "A jacket is how this house speaks in the present tense. Over a set. Over a skirt. After dark.",
    study: "midnight" as const,
    silhouette: "jacket" as const,
    image: "/products/jacket-01.png",
    href: "/shop/jackets",
    cta: "Shop jackets",
  },
  {
    id: "skirt",
    index: "04",
    title: "Skirt culture",
    copy: "Volume, a 15m flare, and skirt-only pieces for when you want the silhouette without the rest of the set.",
    study: "turquoise" as const,
    silhouette: "flare" as const,
    image: "/products/skirt-1.png",
    href: "/shop/skirts",
    cta: "Shop skirts",
  },
  {
    id: "night",
    index: "05",
    title: "After the ceremony",
    copy: "Same clothes. Later hour. The jacket stays on.",
    study: "maroon" as const,
    silhouette: "set" as const,
    image: "/products/blouse-03.png",
    href: "/collections/after-dark",
    cta: "Shop the look",
  },
] as const;
